apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-metrics-app
  labels:
    app: sample-metrics-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sample-metrics-app
  template:
    metadata:
      labels:
        app: sample-metrics-app
    spec:
      containers:
      - name: app
        image: rammurthymalisetti/sample-metrics-app:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: sample-metrics-svc
  labels:
    app: sample-metrics-app
spec:
  selector:
    app: sample-metrics-app
  ports:
  - name: metrics
    port: 8080
    targetPort: 8080
