apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: sample-metrics-sm
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: sample-metrics-app
  namespaceSelector:
    matchNames:
      - default
  endpoints:
  - port: metrics
    path: /metrics
    interval: 15s
    relabelings:
    - sourceLabels: [__meta_kubernetes_service_label_app]
      targetLabel: app