apiVersion: v1
kind: ServiceAccount
metadata:
  name: nginx-controller-autoscaler
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: nginx-controller-autoscaler-role
  namespace: default
rules:
- apiGroups: ["apps"]
  resources: ["deployments", "deployments/scale"]
  verbs: ["get", "list", "watch", "update", "patch"]
- apiGroups: [""]
  resources: ["events"]
  verbs: ["create", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: nginx-controller-autoscaler-rb
  namespace: default
subjects:
- kind: ServiceAccount
  name: nginx-controller-autoscaler
  namespace: default
roleRef:
  kind: Role
  name: nginx-controller-autoscaler-role
  apiGroup: rbac.authorization.k8s.io
