apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-controller-autoscaler
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-controller-autoscaler
  template:
    metadata:
      labels:
        app: nginx-controller-autoscaler
    spec:
      serviceAccountName: nginx-controller-autoscaler
      containers:
      - name: autoscaler
        image: rammurthymalisetti/nginx-controller-autoscaler:latest
        imagePullPolicy: Always
        # --- Health and readiness probes ---
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 2
          failureThreshold: 3

        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 2
          failureThreshold: 3
        # -----------------------------------
        env:
        - name: TARGET_NAMESPACE
          value: "default"
        - name: TARGET_DEPLOYMENT
          value: "nginx-sample-deployment"
        - name: POD_SELECTOR
          value: "app=nginx"
        - name: PROM_URL
          value: "http://kube-prometheus-stack-prometheus.monitoring.svc:9090"
        - name: POLL_INTERVAL
          value: "15s"
        - name: COOLDOWN
          value: "60s"
        - name: MIN_REPLICAS
          value: "2"
        - name: MAX_REPLICAS
          value: "20"
        - name: TARGET_CPU_CORES
          value: "0.2"
        - name: TARGET_MEM_MIB
          value: "300"
        - name: HYSTERESIS_PCT
          value: "10"
        - name: SCALE_STEP_LIMIT
          value: "5"
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-controller-autoscaler-svc
spec:
  selector:
    app: nginx-controller-autoscaler
  ports:
  - name: health
    port: 8081
    targetPort: 8081
