apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: nginxautoscalers.autoscaler.malisetti.dev
spec:
  group: autoscaler.malisetti.dev
  names:
    kind: NginxAutoscaler
    listKind: NginxAutoscalerList
    plural: nginxautoscalers
    singular: nginxautoscaler
    shortNames:
    - nas
  scope: Namespaced
  versions:
  - name: v1alpha1
    served: true
    storage: true
    subresources:
      status: {}
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            required: [targetDeployment]
            properties:
              targetDeployment: { type: string }
              promURL:          { type: string }
              pollInterval:     { type: string }
              cooldown:         { type: string }
              minReplicas:      { type: integer }
              maxReplicas:      { type: integer }
              targetCPU:        { type: number }
              targetMem:        { type: number }
              hysteresisPct:    { type: number }
              stepLimit:        { type: integer }
          status:
            type: object
            properties:
              currentReplicas: { type: integer }
              desiredReplicas: { type: integer }
              lastScaleTime:   { type: string }
